### ISSUE TITLE
Repeating Exception in Backend logs after triggering a mail to be sent

### ISSUE THREAD

**Issue by violoncelloCH** [penpot/penpot#557] opened 2021-02-03 16:35 UTC
**Describe the bug**
After inviting someone to a Team, I get the following log output repeatedly (every few seconds) in the backend log:

<details>

```
penpot-backend_1   | [worker-90] D app.worker - Started task 'sendmail/fea74970-6638-11eb-ac82-de423042f7b9/0'.
penpot-backend_1   | [worker-90] D app.worker - Finished task 'sendmail/fea74970-6638-11eb-ac82-de423042f7b9/0'.
penpot-backend_1   | [async-dispatch-7] E app.worker - Unexpected error ocurried on polling the database (will resume in some instants).
penpot-backend_1   | java.util.concurrent.ExecutionException: java.util.UnknownFormatConversionException: Conversion = ';'
penpot-backend_1   | 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
penpot-backend_1   | 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
penpot-backend_1   | 	at clojure.core$deref_future.invokeStatic(core.clj:2304) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$deref.invokeStatic(core.clj:2324) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$deref.invoke(core.clj:2310) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$map$fn__5885.invoke(core.clj:2757) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RT.seq(RT.java:535) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$seq__5420.invokeStatic(core.clj:139) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core.protocols$fn__8170.invokeStatic(protocols.clj:75) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core.protocols$fn__8170.invoke(protocols.clj:75) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core.protocols$fn__8112$G__8107__8125.invoke(protocols.clj:13) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$reduce.invokeStatic(core.clj:6833) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$run_BANG_.invokeStatic(core.clj:7715) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$run_BANG_.invoke(core.clj:7715) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at app.worker$event_loop_fn_STAR_$fn__15999.invoke(worker.clj:267) ~[?:?]
penpot-backend_1   | 	at next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72) ~[?:?]
penpot-backend_1   | 	at next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51) ~[?:?]
penpot-backend_1   | 	at next.jdbc.transaction$eval6168$fn__6169.invoke(transaction.clj:136) ~[?:?]
penpot-backend_1   | 	at next.jdbc.protocols$eval4968$fn__4969$G__4959__4978.invoke(protocols.clj:57) ~[?:?]
penpot-backend_1   | 	at next.jdbc$transact.invokeStatic(jdbc.clj:271) ~[?:?]
penpot-backend_1   | 	at next.jdbc$transact.invoke(jdbc.clj:263) ~[?:?]
penpot-backend_1   | 	at app.worker$event_loop_fn_STAR_.invokeStatic(worker.clj:254) ~[?:?]
penpot-backend_1   | 	at app.worker$event_loop_fn_STAR_.invoke(worker.clj:252) ~[?:?]
penpot-backend_1   | 	at app.worker$event_loop_fn$fn__16011.invoke(worker.clj:276) ~[?:?]
penpot-backend_1   | 	at app.util.async$thread_call$fn__15047$fn__15048.invoke(async.clj:48) ~[?:?]
penpot-backend_1   | 	at app.util.async$thread_call$fn__15047.invoke(async.clj:48) ~[?:?]
penpot-backend_1   | 	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) ~[jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) ~[jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
penpot-backend_1   | Caused by: java.util.UnknownFormatConversionException: Conversion = ';'
penpot-backend_1   | 	at java.util.Formatter.checkText(Formatter.java:2732) ~[?:?]
penpot-backend_1   | 	at java.util.Formatter.parse(Formatter.java:2708) ~[?:?]
penpot-backend_1   | 	at java.util.Formatter.format(Formatter.java:2655) ~[?:?]
penpot-backend_1   | 	at java.util.Formatter.format(Formatter.java:2609) ~[?:?]
penpot-backend_1   | 	at java.lang.String.format(String.java:3292) ~[?:?]
penpot-backend_1   | 	at clojure.core$format.invokeStatic(core.clj:5733) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$format.doInvoke(core.clj:5727) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:410) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at app.worker$handle_exception.invokeStatic(worker.clj:222) ~[?:?]
penpot-backend_1   | 	at app.worker$handle_exception.invoke(worker.clj:208) ~[?:?]
penpot-backend_1   | 	at app.worker$run_task.invokeStatic(worker.clj:239) ~[?:?]
penpot-backend_1   | 	at app.worker$run_task.invoke(worker.clj:233) ~[?:?]
penpot-backend_1   | 	at app.metrics$instrument_workers_BANG_$fn__16099$fn__16100.invoke(metrics.clj:65) ~[?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:421) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$partial$fn__5860.invoke(core.clj:2634) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[?:?]
penpot-backend_1   | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
penpot-backend_1   | 	... 3 more
```
</details>
This is prossibly due to a misconfiguration of the SMTP parameters, but it would be helpful to have a more clear error message in the logs.

**To Reproduce**
1.  Invite someone to a new Team
2.  realize the mail isn't arrriving and check the penpot logs
3.  see repeating log output as discribed above

**Expected behavior**
Error should not happen or in case of a mail parameter misconfiguration could be clearer to indicate what is wrong exactly.

**Screenshots**
not applicable

**Desktop (please complete the following information):**
not applicable

**Environment (please complete the following information):**
self-hosted

-   OS Version: Ubuntu 16.04
-   Docker / Docker-compose Version:  Docker version 20.10.2
-   Image: official docker-compose (adapted env vars)

**Frontend Stack Trace (if self-hosted)**
not applicable

**Backend Stack Trace (if self-hosted)**
see above

**Comment by violoncelloCH** [comment] 2021-02-03 16:49
So I've now tested every possible combination of port and ssl / tls (restarted the docker containers each time) and the (now two; I invited a second mail) tasks are still there trying to be resent continuously... I'm not sure what to do about it

**Comment by niwinz** [comment] 2021-02-03 21:38
Hi @violoncelloCH
Yeah, the exception error is weird. This is because there are two bugs probably; the second one is masking the first one and the cause is bad use of the logging+formatting. I'm already working on fix of the second bug (it will be landed in the repository tomorrow, and images updated later on the end of the day probably).

When the exception that mask the real problem is fixed, we will see that really happens, and if you need help configuring SMPT I give you some examples on how we are using it; unfortunatelly it is only tested in our environments so feedback from external use is very welcome!

PD: we will configure image building nightly, but for now is a manual process.

**Comment by niwinz** [comment] 2021-02-03 21:43
In our case, we use AWS SES service for sending emails, and for our case we have this configuration:

```sh
PENPOT_SMTP_ENABLED=true
PENPOT_SMTP_HOST=email-smtp.eu-central-1.amazonaws.com
PENPOT_SMTP_PORT=587
PENPOT_SMTP_USERNAME=AAABBBBBCCCDDD
PENPOT_SMTP_PASSWORD=AAbbCCddFFeeeSSSeeeSSSeeefffEEfgg
PENPOT_SMTP_TLS=true
PENPOT_SMTP_DEFAULT_FROM="no-reply@penpot.app"
PENPOT_SMTP_DEFAULT_REPLY_TO="no-reply@penpot.app"
```

**Comment by violoncelloCH** [comment] 2021-02-03 22:31
@niwinz thanks for the answer! Great, so I'll pull the new image tomorrow evening or on friday... if you can, please notify me once the new image is built so I can test and give feedback as soon as possible :)
thanks for the example SMTP configuration! it looks pretty similar to what I've tried... actually my mail provider supports either SMTP with SSL on Port 465 or with STARTTLS on Port 587. I've pretty much tried every possible combination of the port and `PENPOT_SMTP_SSL / _TLS` flags but the mail didn't get sent out... I'm happy to retry with the new image

**Comment by niwinz** [comment] 2021-02-04 16:57
Hi @violoncelloCH 

Latest images are pushed to docker hub and I checked with explicitly set wrong crendetials that the error is corretly printted in the console. Seems works as expected.

In any case, in my experiments I found that my previous example works (environment variables) if hey are interpreted by bash/sh; but from yaml perspective, the `"` (quoting) i have used it incorrectly, so on the end, this is my configuration that I used is:

```yaml
environment:
 - PENPOT_SMTP_ENABLED=true
 - PENPOT_SMTP_HOST=email-smtp.eu-central-1.amazonaws.com
 - PENPOT_SMTP_PORT=587
 - PENPOT_SMTP_USERNAME=AAABBBBBCCCDDD
 - PENPOT_SMTP_PASSWORD=AAbbCCddFFeeeSSSeeeSSSeeefffEEfgg
 - PENPOT_SMTP_TLS=true
 - PENPOT_SMTP_DEFAULT_FROM=Penpot <no-reply@penpot.app>
 - PENPOT_SMTP_DEFAULT_REPLY_TO=Penpot <no-reply@penpot.app>
```
Note the ausense of `"`, this is very important, if you want glob them in quotes, you need to do it to all the line. Example:

```yaml
environment:
 - "PENPOT_SMTP_DEFAULT_REPLY_TO=Penpot <no-reply@penpot.app>"
```

**Comment by violoncelloCH** [comment] 2021-02-04 21:33
okay, so I pulled the new Image and now the repeaded log entries look like this:
<details>

```
penpot-backend_1   | [worker-54] D app.worker - Started task 'sendmail/bb2b79f0-672d-11eb-a44b-531c38518175/0'.
penpot-backend_1   | [worker-54] E app.worker - Unhandled exception on task (id: cea0dc50-672d-11eb-a44b-531c38518175)
penpot-backend_1   | jakarta.mail.MessagingException: Exception reading response
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2476) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:342) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:222) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:243) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send0(Transport.java:228) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send(Transport.java:150) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invokeStatic(emails.clj:173) ~[?:?]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invoke(emails.clj:170) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$handler.invokeStatic(sendmail.clj:66) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$handler.invoke(sendmail.clj:63) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$eval29957$fn__29959$handler__29961.invoke(sendmail.clj:44) ~[?:?]
penpot-backend_1   | 	at app.metrics$wrap_summary$fn__16186.invoke(metrics.clj:229) ~[?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at app.worker$handle_task.invokeStatic(worker.clj:205) ~[?:?]
penpot-backend_1   | 	at app.worker$handle_task.invoke(worker.clj:201) ~[?:?]
penpot-backend_1   | 	at app.worker$run_task.invokeStatic(worker.clj:244) [?:?]
penpot-backend_1   | 	at app.worker$run_task.invoke(worker.clj:240) [?:?]
penpot-backend_1   | 	at app.metrics$instrument_workers_BANG_$fn__16115$fn__16116.invoke(metrics.clj:65) [?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$partial$fn__5860.invoke(core.clj:2634) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at promesa.util.SupplierWrapper.get(util.cljc:37) [?:?]
penpot-backend_1   | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
penpot-backend_1   | Caused by: java.net.SocketTimeoutException: Read timed out
penpot-backend_1   | 	at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
penpot-backend_1   | 	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
penpot-backend_1   | 	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
penpot-backend_1   | 	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
penpot-backend_1   | 	at java.net.Socket$SocketInputStream.read(Socket.java:981) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
penpot-backend_1   | 	at java.io.BufferedInputStream.read(BufferedInputStream.java:263) ~[?:?]
penpot-backend_1   | 	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	... 32 more
penpot-backend_1   | [worker-54] D app.worker - Finished task 'sendmail/bb2b79f0-672d-11eb-a44b-531c38518175/0'.
```
</details>
this is for the follwing config:

```
      - PENPOT_SMTP_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=example@domain.ch
      - PENPOT_SMTP_DEFAULT_REPLY_TO=example@domain.ch
      - PENPOT_SMTP_HOST=asmtp.mail.domain.ch
      - PENPOT_SMTP_PORT=465
      - PENPOT_SMTP_USERNAME=example@domain.ch
      - PENPOT_SMTP_PASSWORD=MySecretPassword
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=true
```
(note, I'm not using quotes anywhere)

so I changed it to the following (as per the supported configuration options of my mail provider, assuming that _SSL is for full SSL and _TLS for STARTTLS):
```
      - PENPOT_SMTP_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=example@domain.ch
      - PENPOT_SMTP_DEFAULT_REPLY_TO=example@domain.ch
      - PENPOT_SMTP_HOST=asmtp.mail.domain.ch
      - PENPOT_SMTP_PORT=587
      - PENPOT_SMTP_USERNAME=example@domain.ch
      - PENPOT_SMTP_PASSWORD=MySecretPassword
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=false
```

and now I'm getting a different error:

<details>

```
penpot-backend_1   | [worker-50] D app.worker - Started task 'sendmail/85a2e0a0-672f-11eb-98b1-00b669b3c9fb/0'.
penpot-backend_1   | [worker-50] E app.worker - Unhandled exception on task (id: 872f4d00-672f-11eb-98b1-00b669b3c9fb)
penpot-backend_1   | jakarta.mail.AuthenticationFailedException: 535 Incorrect authentication data
penpot-backend_1   | 
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:947) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:342) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:222) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Service.connect(Service.java:243) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send0(Transport.java:228) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at jakarta.mail.Transport.send(Transport.java:150) ~[jakarta.mail-2.0.0.jar:2.0.0]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invokeStatic(emails.clj:173) ~[?:?]
penpot-backend_1   | 	at app.util.emails$send_BANG_.invoke(emails.clj:170) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$handler.invokeStatic(sendmail.clj:66) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$handler.invoke(sendmail.clj:63) ~[?:?]
penpot-backend_1   | 	at app.tasks.sendmail$eval29957$fn__29959$handler__29961.invoke(sendmail.clj:44) ~[?:?]
penpot-backend_1   | 	at app.metrics$wrap_summary$fn__16186.invoke(metrics.clj:229) ~[?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.2.jar:?]
penpot-backend_1   | 	at app.worker$handle_task.invokeStatic(worker.clj:205) ~[?:?]
penpot-backend_1   | 	at app.worker$handle_task.invoke(worker.clj:201) ~[?:?]
penpot-backend_1   | 	at app.worker$run_task.invokeStatic(worker.clj:244) [?:?]
penpot-backend_1   | 	at app.worker$run_task.invoke(worker.clj:240) [?:?]
penpot-backend_1   | 	at app.metrics$instrument_workers_BANG_$fn__16115$fn__16116.invoke(metrics.clj:65) [?:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at clojure.core$partial$fn__5860.invoke(core.clj:2634) [clojure-1.10.2.jar:?]
penpot-backend_1   | 	at promesa.util.SupplierWrapper.get(util.cljc:37) [?:?]
penpot-backend_1   | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.36.v20210114.jar:9.4.36.v20210114]
penpot-backend_1   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
penpot-backend_1   | [worker-50] D app.worker - Finished task 'sendmail/85a2e0a0-672f-11eb-98b1-00b669b3c9fb/0'.
```
</details>

**Comment by niwinz** [comment] 2021-02-04 22:01
Nice to know that now the errors are raised correctly.

Now loking at the errors, the first one seems like is bad conmbination of port and ssl; 
The second one seems like a correct combination of port and tls, but for some reason it does not works. I'm pretty sure that your credentials are correct but I don't know why this error happens. I have seen this 535 error on my experiments with wriong credentials so it is expected error...

In any case, we are using a standard java mail library so, knowing that it works with AWS SES we need to consider more options that a posible bug in emal sending subsistem. Sincerelly, right now I don't know how I can help you... can you try with other provider just for test?

**Comment by violoncelloCH** [comment] 2021-02-04 22:08
Okayokay, I figured out that I indeed made a mistake on the credentials... so with the second configuration it's working now :tada: 
however for the first case I'm still wondering why it isn't working that way... my mail provider supports port 465 with SSL (it clearly does as the same account works in my mail client with port 465 and SSL)... any idea on that? (I generally prefer complete encryption over STARTTLS)
also slightly confusing is that the frontend reports the mail to be "sent successfully" almost immediately even though the worker fails later on...

**Comment by violoncelloCH** [comment] 2021-02-04 22:21
so I've just tried it with a completely different mail provider - same result: 
Mail sending works on port `587` with the `_TLS` flag set to `true`, 
but it fails with the same `Exception reading response` when using port `465` with either the `_SSL` or the `_TLS` flag set to `true`

**Comment by niwinz** [comment] 2021-02-05 08:54
Nice to know that it finally worked; (in any case TLS is recommended over SSL)

I need to research why it does not work with SSL.

**Comment by violoncelloCH** [comment] 2021-02-05 09:57
I see; I was wrong on this (the assumption that the implicit encryption should be preferred) 
I just did some research and found out that port 465 for SMTPS (implicit encryption) was actually deprecated a long time ago in favor of port 587 for SMTP with STARTTLS (encryption negotiated after connection is already established)... Nevertheless many (if not almost all) clients still support the deprecated SMTPS on 465, so I'd say it'd make sense to at least state in the docs that STARTTLS (on default port 587) should be used with Penpot

EDIT: Ref: https://en.wikipedia.org/wiki/SMTPS (specifically the *History* section)

**Comment by niwinz** [comment] 2021-02-05 10:54
i'll take note and update the docs accordingly

**Comment by niwinz** [comment] 2021-02-05 10:54
I think we can consider this issue solved.

**Closed as completed by niwinz** 2021-02-05 10:54 UTC
Labels: bug

**Comment by violoncelloCH** [comment] 2021-02-06 00:37
yup, fine by me...
@niwinz feel free to ping me for a review of the doc changes :)
