### ISSUE TITLE
Export function is not working in self-hosting

### ISSUE THREAD

**Issue by Enrico204** [penpot/penpot#1103] opened 2021-07-22 08:14 UTC
**Describe the bug**
I'm using the docker-compose example from the documentation.

In a workspace, when clicking on "Export" -> "Export shape", the export action returns an internal error. The docker-compose log suggests a timeout error.

**To Reproduce**
1.  Download and start docker-compose files as stated in documentation: https://help.penpot.app/technical-guide/getting-started/
2.  Log-in (guest or standard account, it doesn't matter)
3.  Create a new draft, draw something, import an image, etc
4.  Click on any shape, go to the left toolbar and try to export the shape

**Expected behavior**
I'm expecting a save-file popup from the browser for the rendered image.

**Screenshots**
![image](https://user-images.githubusercontent.com/8115660/126608006-ef83fbc4-4f7a-45dd-b597-457210371f62.png)

**Desktop:**

-   OS: Debian 10
-   Browser: Firefox
-   Version: 90.0

**Environment:**
I'm using the docker-compose example from the documentation: https://help.penpot.app/technical-guide/getting-started/
No changes to any file.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Debian 10

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: Docker version 20.10.7-ce, build f0df350, docker-compose version 1.24.1, build 4667896b
-   Image: `penpotapp/*:latest` (as in the docker-compose file)

**Frontend Stack Trace**

<details>

```
POST http://localhost:9001/export [HTTP/1.1 500 Internal Server Error 30063ms]
```

</details>

**Backend Stack Trace (if self-hosted)**

<details>

```
penpot-exporter_1  | [app.http.impl] {:msg "Unexpected error", :error #object[Error Error: Timeout hit: 30000], :line 49}
penpot-exporter_1  | Error: Timeout hit: 30000
penpot-exporter_1  |     at Object.<anonymous> (/opt/app/node_modules/puppeteer-cluster/dist/util.js:69:23)
penpot-exporter_1  |     at Generator.next (<anonymous>)
penpot-exporter_1  |     at fulfilled (/opt/app/node_modules/puppeteer-cluster/dist/util.js:5:58)
penpot-frontend_1  | 172.24.0.1 - - [22/Jul/2021:08:03:48 +0000] "POST /export HTTP/1.1" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
penpot-exporter_1  | [app.renderer.bitmap] {:uri "http://penpot-frontend/#/render-object/ee73bba0-eabe-11eb-bc4c-6e159e2f48af/ee73bba1-eabe-11eb-bc4c-6e159e2f48af/ca8af6d0-eabf-11eb-86eb-fbeb261aa176", :line 42}
```

</details>

**Additional context**
Nothing else at the moment.

**Comment by niwinz** [comment] 2021-07-28 11:47
I found the cause and I will fix it ASAP

**Comment by niwinz** [comment] 2021-07-29 12:40
Updated the `1.7.1-alpha` and `latest` tags on dockerhub.
The issue should be fixed.

**Comment by niwinz** [comment] 2021-07-29 12:40
Also, ensure change the storage settings on config.env: https://github.com/penpot/penpot/issues/1120#issuecomment-889092504

**Closed as completed by niwinz** 2021-07-29 12:40 UTC
Labels: bug

**Comment by Enrico204** [comment] 2021-08-02 09:17
Confirmed, the issue is fixed :-)
