### ISSUE TITLE
Error by typing "ê"

### ISSUE THREAD

**Issue by edas** [penpot/penpot#711] opened 2021-02-27 19:07 UTC
**Describe the bug**

Typing "ê" (french letter) on a french keyboard results in an internal error. This letter is obtained by typing the dead letter "^" then typing "e". 

I don't have the error by copy-pasting the character directly. It seems linked to the formation of the character through a dead letter.

**To Reproduce**

1.  Create a text box
2.  Type any text, then the "^" dead letter followed by "e"
3.  See error

**Expected behavior**

No error ;-)

-   Mac OS X 10.15.7
-   Browser Firefox desktop, 85.0.2

**Environment (please complete the following information):**

SAAS (https://design.penpot.app)

**Comment by keunes** [comment] 2021-02-28 10:54
Duplicate of #688

**Closed as completed** 2021-02-28 16:23 UTC
Labels: bug
