### ISSUE TITLE
Error When Duplicating Board

### ISSUE THREAD

**Issue by nrcerna** [penpot/penpot#986] opened 2021-05-26 23:33 UTC
**Describe the bug**
I was working on a board and after finished, I tried to duplicate and I got this:
![image](https://user-images.githubusercontent.com/29005884/119743843-f9edd180-be47-11eb-99b9-8949eb39fd88.png)

**To Reproduce**
1.  Go to the left panel
2.  Click on the artboard
3.  Scroll down to Duplicate
4.  See error

**Expected behavior**
I did duplicate before without any issue

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Edge

**Environment (please complete the following information):**
Using SAAS (https://design.penpot.app) 

**Additional context**

**Comment by elhombretecla** [comment] 2021-05-27 06:53
Hi @nrcerna :)

We couldn't reproduce this bug. Could you send us a console report or more info about it?
If you can send to us the file link (share link) to check it in deep it would help.

Thank you very much!

**Comment by elhombretecla** [comment] 2021-07-07 15:13
We are unable to reproduce this error. We proceed to close this bug. We will see how to proceed if it happens in the future. Thank you :)

**Closed as completed by elhombretecla** 2021-07-07 15:13 UTC
Labels: bug
