### ISSUE TITLE
Custom font does not work in firefox

### ISSUE THREAD

**Issue by razzeee** [penpot/penpot#1110] opened 2021-07-23 13:09 UTC
**Describe the bug**
If I open our penpot workspace, that's using a custom font with firefox, it does not use the correct custom font. Edge and chrome seem fine so far.

Sometimes, when we open it up, it seems to use the correct font, but clicking anywhere/on text will bring back the default font.

**To Reproduce**
(You need to have the font installed on your local system)
1.  Go to 'Fonts'
2.  Add a font 'Frutiger Neue LT Pro'
3.  Add the font to a design
4.  Open the penpot with firefox
5. Check the font, sometimes it get's rendered correctly, but if you mouse over it, it will jump back to the default font

**Expected behavior**
The correct font should be used

**Desktop (please complete the following information):**

-   OS: Fedora, but also tested it on Windows
-   Browser: Firefox
-   Version: 90.0.1

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by elhombretecla** [comment] 2021-07-26 05:43
Hi @Razzeee thanks for your feedback and sorry for de inconvenince

We couldn't reproduce this bug. Could you give us more information or images/videos/gifs showing the problem?

Thank you again.

**Comment by razzeee** [comment] 2021-07-26 07:08
![Screencast from 26 07 2021 09 02 56](https://user-images.githubusercontent.com/5943908/126947135-b8287d93-d328-4173-aea6-ae93fe9ebfba.gif)
(don't mind the screencast quality, I had to reencode the webm to gif...)

The first font showing is the correct one, if I then mouse over it, it will be replaced by some default one, with serifs.

I'm not sure which other infos would be useful.

**Comment by niwinz** [comment] 2021-07-27 12:18
hi @Razzeee , if you can, send us please the workspace url of the file that has this problem,we need to research more on it (privatelly, on info@penpot.app)

**Comment by Razzeee** [comment] 2021-07-27 12:20
should be `1cdd02f0-e63a-11eb-ac29-4c4b7a420f0b`

**Comment by razzeee** [comment] 2021-07-27 12:23
I've also just tested with a private tab, to make sure it's not an extension and it still shows the problem.

**Comment by niwinz** [comment] 2021-08-19 08:54
We have had some unexpected issue when the font is uploaded from windows. Browser (chrome or firefox, ...) running on windows os for some reeason reported incorrectly the font mimetype and make the font upload broken. It is should be fixed but you will need to reupload the font again because previous upload is broken.

Sorry for the inconvenience.

**Closed as completed by niwinz** 2021-08-19 08:54 UTC
Labels: bug

**Comment by razzeee** [comment] 2021-08-19 15:12
As far as I know my team member used a macbook and chrome to upload this.

**Comment by niwinz** [comment] 2021-08-19 21:12
I know that issue is reproducible with windows, but it can affect other platforms. If this still persists, maybe is a different issue.
