### ISSUE TITLE
Text does not display on Firefox based browsers

### ISSUE THREAD

**Issue by lrq3000** [penpot/penpot#1081] opened 2021-07-11 15:12 UTC
**Describe the bug**
Text does not display on Firefox based browsers, but they do display on Chrome browsers.

**To Reproduce**
Have a look at: https://design.penpot.app/#/view/441c1550-c424-11eb-8557-f55ab9adbb41/d0e73e20-e124-11eb-a77a-195c36c76d76?token=42eqNw4QBfdJNSiw-eeueg&index=4

On Chrome, the text in the menu is white-ish. Try to open the same link on a Firefox based browser (whether Firefox on desktop or or smartphones or Opera), and the text will not display. This isn't the only artboard where this happens, all artboards are affected. Some text is not affected but most text (created via the text tool or by reusing components from the Penpot Design library) is.

**Expected behavior**
Text should display.

**Screenshots**

What should display and is displayed on Chrome:

![penpot-text-ok](https://user-images.githubusercontent.com/1118942/125200344-eb7a3e80-e26a-11eb-9d4c-b325794b16a6.png)

What it shows on Firefox:

![penpot-text-ko](https://user-images.githubusercontent.com/1118942/125200347-f339e300-e26a-11eb-80d8-6381453f7ab8.png)

**Desktop (please complete the following information):**

-   OS: Windows 10, Android 9
-   Browser: Firefox based browsers (Firefox desktop, Firefox mobile, Opera Touch on mobile)
-   Version: latest

**Smartphone (please complete the following information):**

-   Device: Huawei P10
-   OS: Android 9
-   Browser: Firefox based browsers (Firefox mobile, Opera Touch on mobile)
-   Version: latest

**Environment (please complete the following information):**
SAAS

**Comment by myfunnyandy** [comment] 2021-07-13 11:47
Thanks for the report, we've added it to Taiga an will take a look at it soon https://tree.taiga.io/project/penpot/issue/1889

**Comment by hirunatan** [comment] 2021-07-13 13:33
@lrq3000 I have examined your files, and find that the text that does not show is painted with the same color of the background.

I'm not sure of how can you see the texts in chrome (for me, texts are invisible in any browser). Could you try again, please? And check if the colors of the text are ok in the options panel at the workspace.

Perhaps this is a problem with the synchronization of colors in your shared library. If the texts are still missing, could you manually change the color of one of them, to set a direct color and not a library one?

**Comment by lrq3000** [comment] 2021-07-16 03:20
@hirunatan Thank you for your fast reply! Good catch!

I tried changing manually the color with the color wheel, and it works!

However, there is I think a bug, or an undocumented feature. Because I did not use the color palette, I used the color picker all the time. And it seems the color picker picks up the background color here for some reason, totally disregarding the text, but the text is clearly there with another color!

Here is a screenshot (that did not capture my cursor so I replaced it with a red arrow to represent where my color picker cursor was):

![penpot-color-picker-doesnt-see-the-text](https://user-images.githubusercontent.com/1118942/125886565-c5cf1c1b-e3c9-4cb2-8fc9-266b186ddfff.png)

As you can see, the color picker doesn't show the text. But on screen I can see the text in a different color. This is very strange.

Also if it can help you debug this faster, since now there is an expert feature :D Here is my exported project, feel free to tamper it!

https://github.com/Circadiaware/circalog/blob/main/docs/Circalog_export-shared-libs_penpot-v1.7alpha.penpot

**Comment by lrq3000** [comment] 2021-07-16 03:21
PS: keep in mind the text displays on Chrome! I use the editor only in Chrome.

**Comment by hirunatan** [comment] 2021-07-28 07:48
@lrq3000 could you check if the problem with the color picker is an issue about the cursor position? Perhaps when you move the pick cursor over the text, it is taking the color of some pixels above or below, and this is why is picking the background color.

It would be very useful for me to have your file. I see that the link you shared is now broken. Could you send me again the exported file? Thanks!

**Comment by lrq3000** [comment] 2021-07-28 18:09
Yes I am sure it's not a mis-selected pixel, i have redone my whole project
now by entering manually the color value. For some reason, most of the text
objects have this issue, they are unpickable, even text objects i created
with the text tool, not by components nor copy paste.

After investigating a bit more, it seems that there is another "companion
bug" with the preview color shown in the color picker AND in penpot editor
being wrong (ie, showing a light grey color) , but the value is correct
(ie, near black color, the one of the background). When playing the mockup,
the text is colored with the real value, but in the editor it's the
incorrect color that is displayed. This issue happens with other colors as
well, it seems the color picker preview color is not reliable.

The export file will likely be more helpful for you to debug this at this
stage than my profane description. I'm sorry about the dead link, i
recently reorganized my repo, here is the new path to the export:

https://github.com/Circadiaware/circalog/blob/main/docs/penpot_backups/Circalog_20210711_export-shared-libs_penpot-v1.7alpha.penpot

Please let me know if i can help with anything else, and thank you very
much for looking into it!

Le mer. 28 juil. 2021 à 09:48, Andrés Moya ***@***.***> a
écrit :

**Comment by hirunatan** [comment] 2021-07-29 10:45
Thanks. I've been able to import your file.

But I can't reproduce the problem. I've tried to pick some texts and it always pick the same color that I'm seeing at the main viewport.

Could yo point me to one specific text that manifests this behavior in your file? And put me a screenshot?

**Comment by lrq3000** [comment] 2021-08-19 02:12
Hello, thank you for following up on this issue.

I'm sorry for the delay.

Please find below one of the pages where the issue happens, I have made a live public link to the project file I shared above:

https://design.penpot.app/#/view/d92a1f80-e1ec-11eb-97a9-7472ffaca84b/d0e73e20-e124-11eb-a77a-195c36c76d76?token=hC2Nxm9r6ZF8iTcl-kegtg&index=4

The screenshots are the ones shown in my opening post above.

Normally if you open the link with Firefox, whether on desktop or mobile, you should see no text, but with Chrome everything should display fine.

**Comment by hirunatan** [comment] 2021-08-19 10:24
Honestly, I'm a bit puzzled with your file :)

The reason for you not seeing the texts, is that the text color is fixed to #2c2fea, that is the same as the dropdown background:

![circa](https://user-images.githubusercontent.com/1483050/130052727-7f26a936-5dd7-446c-a052-7a8d5c84e16d.png)

This is also the reason of that the color picker does not pick any other color than this one. The actual question is why are yo able to see the texts in your Chrome (I've tested it in Chrome, Chromium and Firefox and the text is not visible in any of them).

My hypothesis is that in the past you had a different color for this texts, and you browser has cached the frames some way, and still shows the old image. But the real file has invisible texts because the color is the same of the background.

If you manually change the text color, do you see it now?

**Comment by hirunatan** [comment] 2022-01-21 10:35
Hi. I'm closing this issue. If you experience this problem again, please reopen it.

**Closed as completed by hirunatan** 2022-01-21 10:35 UTC
Labels: bug, managed on taiga
