### ISSUE TITLE
Loosing permissions to a team I used to access

### ISSUE THREAD

**Issue by numahell** [penpot/penpot#678] opened 2021-02-21 20:35 UTC
**Describe the bug**
I created a team, or someone invited me. I could access to this team, create new draft or project, editing existing ones.
But then for no reason I don't have the permission anymore.
For the one I created I was the only member.

**To Reproduce**
1.  Create a team
2.  Add files or project
3.  Logout
4.  Login : teams are no more available

**Expected behavior**
Access rights to my teams

**Screenshots**
NA

**Desktop (please complete the following information):**

-   OS: Linux Ubuntu 20.10
-   Browser Firefox 
-   Version 85.0.1

**Environment (please complete the following information):**
Demo instance

**Additional context**
Congratulations this tool is really awesome !

**Comment by niwinz** [comment] 2021-02-22 12:48
Hi @numahell 
Welcome!

Few questions:
- Can you reproduce this behavior consistently? (i mean, if you repeat yourself this more than one time).
- What you mean with "demo instance"?

Thanks.

**Comment by niwinz** [comment] 2021-02-24 16:32
Unable to reproduce, so closing. Reopen if this happens again.

**Closed as completed by niwinz** 2021-02-24 16:32 UTC
Labels: bug
