### ISSUE TITLE
Internal Error when entering non-English text on empty text box

### ISSUE THREAD

**Issue by aqiank** [penpot/penpot#656] opened 2021-02-17 05:26 UTC
**Describe the bug**
It seems like when I switch to non-English input method, the placeholder text on the text box stays and I'm typing additional text to the left of it. Then when I press Enter to finalize the text, it crashes the app.

**To Reproduce**
1.  Create a text box with large enough size
2.  Switch input method to Japanese / Chinese
3.  Type some text and finalize them with Enter
4.  Internal Error screen pops up

**Expected behavior**
The placeholder text disappears when I type and app doesn't crash when I press Enter.

**Screenshots**
I have uploaded a video showing the issue at https://youtu.be/_f-zoTR5d3E

**Desktop (please complete the following information):**

-   OS: Fedora 33
-   Browser: Brave
-   Version: v1.0.0-alpha

**Additional context**
My colleague tried on macOS with the same browser as well and it seems the same thing happens.

**Comment by Alotor** [comment] 2021-02-17 09:28
Thanks for the report. We will give this crash priority and fix it ASAP. I'll let you know when it's fixed.

**Comment by Alotor** [comment] 2021-02-17 11:28
I've been testing and it's a bug in the library we use for the text editing: https://github.com/ianstormtaylor/slate

I'm checking to see if we can do something at least to minimize the problem on our side.

**Comment by Alotor** [comment] 2021-02-17 11:36
This is the issue we're looking at: https://github.com/ianstormtaylor/slate/issues/4031

Fortunately there is a couple of workarounds. I've tried to disable the placeholder completely and the problem disappears. In that report they propose a couple of workarounds.

**Comment by Alotor** [comment] 2021-02-17 13:18
@aqiank We've deployed a fix for this issue. Can you try and tell me if the issue still persists?

**Comment by edas** [comment] 2021-02-17 18:24
Not sure it is linked because it's not japanese but I have a reproducible crash each time I try to enter a "ô", which in french is by typing the dead key "^" following by a "o".

**Comment by aqiank** [comment] 2021-02-17 18:36
@Alotor The error still seems to happen when I use https://design.penpot.app

**Comment by niwinz** [comment] 2021-02-19 10:48
We have deployed (few minnutes ago) a possible fix for this problem. We have removed completly the placeholders that seems causing this issue. Please, can you check it again? (ensure you have refreshed the penpot application tab).

**Comment by aqiank** [comment] 2021-02-19 12:17
@niwinz Yes, it seems like it doesn't happen anymore. Thanks for the fix!

**Comment by niwinz** [comment] 2021-02-19 12:23
\o/ nice, thanks for confirm.

**Closed as completed by niwinz** 2021-02-19 12:23 UTC
Labels: bug
