### ISSUE TITLE
Grid is disabled when pages are changed.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#80] opened 2017-03-09 10:04 UTC
![grid](https://cloud.githubusercontent.com/assets/4901306/23745369/fe6d1b66-050b-11e7-8156-5c65b54ebea1.gif)

**Comment by niwinz** [comment] 2017-03-09 10:08
That is expected.

**Comment by elhombretecla** [comment] 2017-03-09 10:14
Yep.

Every page grid setup is included in its own storage. So each page could have different grid settings, visibility of the grid included :)

**Comment by niwinz** [comment] 2017-03-09 10:15
And the grid visibility is just a flag on workspace. So if you load an other page, the workspace is reinitialized in order to not preserve the other page state.

**Comment by studiospring** [comment] 2017-03-09 10:48
Sorry, my gif was not very clear. Here is a better one.

![grid](https://cloud.githubusercontent.com/assets/4901306/23746943/fe28e35a-0511-11e7-96ab-6a17af50f0a9.gif)

Hopefully you can see that when I return to page 0, the page 0 grid is disabled, even though it was showing before I switched to page last.

**Comment by niwinz** [comment] 2017-03-21 09:50
Yeah, this is the expected behavior. As I said, the grid visibility is a flag on the workspace. And it is reset on page change. Feel free to open an enhancement to make the flags page aware, but at this moment it is low priority.

**Comment by studiospring** [comment] 2017-03-21 22:16
Ok, it seems unintuitive to me, but since it is low priority I will leave it for now.

**Comment by elhombretecla** [comment] 2017-03-22 08:48
We did this way because you could have different grid settings depending on the stuff you're working on. Probably you need different grid sizing depending on a mobile or desktop design on the same project.

**Comment by studiospring** [comment] 2017-03-22 10:06
@elhombretecla, having different grid settings for different pages makes sense. But disabling my grid  when I change pages does not.

**Comment by niwinz** [comment] 2017-03-22 10:21
@studiospring after a brief meeting with @elhombretecla we have decided change the current approach to a slightly different one. That consists on:
- The grid visibility and grid magnet will become a workspace flags (the flags will not be reset on page changes).
- The grid size and the grid color will be page properties.
- You should be able activate the magnet and grid separately, allowing the user having magnet without the visible grid.

**Comment by studiospring** [comment] 2017-03-22 10:53
@niwinz that makes a lot more sense to me. Thanks.

**Comment by niwinz** [comment] 2017-03-25 18:49
Should be fixed in master.

**Closed as completed** 2017-03-25 18:57 UTC
Labels: enhancement
