### ISSUE TITLE
Element highlight is rotated, though rotation = 0

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#715] opened 2021-02-28 10:59 UTC
**Describe the bug**
The turquoise highlight of an element is rotated, even though the rotation of the element is set to 0. The element itself (what you can see) doesn't have a rotation - it seems to be just the highlight.

**To Reproduce**
Don't know - it suddenly was like this. I just selected the element.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11229646/109416050-41390300-79bc-11eb-9342-a4acaf448f53.png)

Rotation 5 degree added:
(The highlight seems 'less' rotated, while the actual element now is rotated. Note that there's a screenshot behind the Android navigation bar that now shows another navigation bar, because rotating the element created 'blank' areas.)
![image](https://user-images.githubusercontent.com/11229646/109416141-b4427980-79bc-11eb-9b18-73da68f003dc.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04
-   Browser: Firefox 86.0

Using Penpot SAAS.

**Comment by claragvinola** [comment] 2021-03-02 06:55
Hi again! have you tried to unblock de layer group before rotate?

**Comment by keunes** [comment] 2021-03-02 09:09
Hi @claragvinola No. But the thing is: I don't want it rotated :) So there's just something off with the element highlight/indication for some reason.

**Comment by Alotor** [comment] 2021-03-02 10:30
@keunes Thanks for the report. I'll need you to do something so we can debug this issue.

Just copy (Ctrl+c) the rotated shape and paste in a text file. Upload that file here please. 

This will give use the "internal" representation of the object and we can check what's wrong.

**Comment by keunes** [comment] 2021-03-02 13:05
Sure, please see attached. Thanks!
[Android bar-5.txt](https://github.com/penpot/penpot/files/6068778/Android.bar-5.txt)

**Comment by Alotor** [comment] 2021-03-02 14:04
Great! I'll try to see if I can see what happened.

In the meantime, to work around your issue, just "Ungroup" the mask and then create the mask again. This will fix the issue.

**Comment by Alotor** [comment] 2021-03-02 14:09
Actually, with further testing I've seen that the problem is that the rectangle that masks your image is "flipped". This is what causes the selection to be rotated.

The best way is just to unmaks, delete the old rectangle (or you can also right-click and "flip horizontal" on the old one) and then create the mask again.

I've located the issue so it will be fixed on the next release.

**Comment by keunes** [comment] 2021-03-02 21:02
Unlocking, and horizontally flipping the rectangle didn't seem to have any effect. However, deleting the rectangle and recreating the mask worked. Thanks!

**Closed as completed** 2021-03-08 21:48 UTC
Labels: bug
